
import java.awt.Color;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mehme
 */
public class JFrame_manager_dashbord extends javax.swing.JFrame {
    
    Color DefaultColor ,ClickColor;

    /**
     * Creates new form JFrame_manager
     */
    public JFrame_manager_dashbord() {
        initComponents();
        ImageIcon img = new ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\dashboard.png");
        this.setIconImage(img.getImage());
        DefaultColor = new Color(248,248,255);
        ClickColor = new Color(117,255,17);
        JInternalFrame_employee frame_employee = new JInternalFrame_employee();
        
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_employee).setVisible(true);
        
        BT_employees.setBackground(ClickColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BT_exit = new javax.swing.JButton();
        panel_butons1 = new javax.swing.JPanel();
        BT_employees = new javax.swing.JButton();
        BT_departmens = new javax.swing.JButton();
        BT_suppliers = new javax.swing.JButton();
        BT_customers = new javax.swing.JButton();
        BT_products = new javax.swing.JButton();
        BT_production_machines = new javax.swing.JButton();
        BT_raw_materials = new javax.swing.JButton();
        BT_orders = new javax.swing.JButton();
        panel_butons2 = new javax.swing.JPanel();
        BT_product_simulations = new javax.swing.JButton();
        BT_shops = new javax.swing.JButton();
        BT_transport_vehicles = new javax.swing.JButton();
        BT_account = new javax.swing.JButton();
        BT_job_applications = new javax.swing.JButton();
        BT_business_partners = new javax.swing.JButton();
        BT_sales_persons = new javax.swing.JButton();
        BT_managers = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel_jframe_areas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(39, 64, 139));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 15, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FACTORY MANAGEMENT SYSTEM");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\project-management (1).png")); // NOI18N

        BT_exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\close_window.png")); // NOI18N
        BT_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(965, 965, 965)
                        .addComponent(BT_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BT_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panel_butons1.setBackground(new java.awt.Color(58, 95, 205));

        BT_employees.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\employees1.png")); // NOI18N
        BT_employees.setText("EMPLLOYEES");
        BT_employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_employeesMousePressed(evt);
            }
        });
        BT_employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_employeesActionPerformed(evt);
            }
        });

        BT_departmens.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\department.png")); // NOI18N
        BT_departmens.setText("DEPARTMENTS");
        BT_departmens.setMaximumSize(new java.awt.Dimension(93, 23));
        BT_departmens.setMinimumSize(new java.awt.Dimension(93, 23));
        BT_departmens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_departmensMousePressed(evt);
            }
        });
        BT_departmens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_departmensActionPerformed(evt);
            }
        });

        BT_suppliers.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\supplier.png")); // NOI18N
        BT_suppliers.setText("SUPPLIERS");
        BT_suppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_suppliersMousePressed(evt);
            }
        });
        BT_suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_suppliersActionPerformed(evt);
            }
        });

        BT_customers.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\customer (1).png")); // NOI18N
        BT_customers.setText("CUSTOMERS");
        BT_customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_customersMousePressed(evt);
            }
        });
        BT_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_customersActionPerformed(evt);
            }
        });

        BT_products.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\automobile.png")); // NOI18N
        BT_products.setText("PRODUCTS");
        BT_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_productsMousePressed(evt);
            }
        });
        BT_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_productsActionPerformed(evt);
            }
        });

        BT_production_machines.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\robotic-machine.png")); // NOI18N
        BT_production_machines.setText("PRODUCTION MACHINES");
        BT_production_machines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_production_machinesMousePressed(evt);
            }
        });
        BT_production_machines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_production_machinesActionPerformed(evt);
            }
        });

        BT_raw_materials.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\raw-materials.png")); // NOI18N
        BT_raw_materials.setText("RAW MATERIALS");
        BT_raw_materials.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_raw_materialsMousePressed(evt);
            }
        });
        BT_raw_materials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_raw_materialsActionPerformed(evt);
            }
        });

        BT_orders.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\icons8-purchase-order-32.png")); // NOI18N
        BT_orders.setText("ORDERS");
        BT_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_ordersMousePressed(evt);
            }
        });
        BT_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ordersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_butons1Layout = new javax.swing.GroupLayout(panel_butons1);
        panel_butons1.setLayout(panel_butons1Layout);
        panel_butons1Layout.setHorizontalGroup(
            panel_butons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_butons1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_butons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_employees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_departmens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_suppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_production_machines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_raw_materials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_butons1Layout.setVerticalGroup(
            panel_butons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_butons1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BT_employees, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_departmens, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_customers, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_products, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_production_machines, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_raw_materials, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_butons2.setBackground(new java.awt.Color(58, 95, 205));

        BT_product_simulations.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\simulator.png")); // NOI18N
        BT_product_simulations.setText("PRODUCT SIMULATIONS");
        BT_product_simulations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_product_simulationsMousePressed(evt);
            }
        });
        BT_product_simulations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_product_simulationsActionPerformed(evt);
            }
        });

        BT_shops.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\car_1.png")); // NOI18N
        BT_shops.setText("SHOPS");
        BT_shops.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_shopsMousePressed(evt);
            }
        });
        BT_shops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_shopsActionPerformed(evt);
            }
        });

        BT_transport_vehicles.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\vehicle.png")); // NOI18N
        BT_transport_vehicles.setText("TRANSPORT VEHICLES");
        BT_transport_vehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_transport_vehiclesMousePressed(evt);
            }
        });
        BT_transport_vehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_transport_vehiclesActionPerformed(evt);
            }
        });

        BT_account.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\accounting.png")); // NOI18N
        BT_account.setText("ACCOUNT");
        BT_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_accountMousePressed(evt);
            }
        });
        BT_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_accountActionPerformed(evt);
            }
        });

        BT_job_applications.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\cv.png")); // NOI18N
        BT_job_applications.setText("JOB APPLICATIONS");
        BT_job_applications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_job_applicationsMousePressed(evt);
            }
        });
        BT_job_applications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_job_applicationsActionPerformed(evt);
            }
        });

        BT_business_partners.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\category.png")); // NOI18N
        BT_business_partners.setText("CAR CATEGORY");
        BT_business_partners.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_business_partnersMousePressed(evt);
            }
        });
        BT_business_partners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_business_partnersActionPerformed(evt);
            }
        });

        BT_sales_persons.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\worker.png")); // NOI18N
        BT_sales_persons.setText("SALES PERSONS");
        BT_sales_persons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_sales_personsMousePressed(evt);
            }
        });
        BT_sales_persons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_sales_personsActionPerformed(evt);
            }
        });

        BT_managers.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\manager.png")); // NOI18N
        BT_managers.setText("MANAGERS");
        BT_managers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_managersMousePressed(evt);
            }
        });
        BT_managers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_managersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_butons2Layout = new javax.swing.GroupLayout(panel_butons2);
        panel_butons2.setLayout(panel_butons2Layout);
        panel_butons2Layout.setHorizontalGroup(
            panel_butons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_butons2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_butons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_product_simulations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_shops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_transport_vehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_job_applications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_business_partners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_sales_persons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_managers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_butons2Layout.setVerticalGroup(
            panel_butons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_butons2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(BT_product_simulations, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_shops, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_transport_vehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_account, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_job_applications, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_business_partners, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_sales_persons, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_managers, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WAS DONE AND DEVELOPED BY MEHMET ŞENER");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(518, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(452, 452, 452))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        panel_jframe_areas.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panel_jframe_areasLayout = new javax.swing.GroupLayout(panel_jframe_areas);
        panel_jframe_areas.setLayout(panel_jframe_areasLayout);
        panel_jframe_areasLayout.setHorizontalGroup(
            panel_jframe_areasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_jframe_areasLayout.setVerticalGroup(
            panel_jframe_areasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_butons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_jframe_areas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_butons2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_butons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_butons2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_jframe_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BT_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_exitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_BT_exitActionPerformed

    private void BT_employeesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_employeesMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(ClickColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_employeesMousePressed

    private void BT_departmensMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_departmensMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(ClickColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_departmensMousePressed

    private void BT_suppliersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_suppliersMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(ClickColor);
        BT_transport_vehicles.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_BT_suppliersMousePressed

    private void BT_customersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_customersMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(ClickColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
        
    }//GEN-LAST:event_BT_customersMousePressed

    private void BT_productsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_productsMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(ClickColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
        
    }//GEN-LAST:event_BT_productsMousePressed

    private void BT_production_machinesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_production_machinesMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(ClickColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
        
    }//GEN-LAST:event_BT_production_machinesMousePressed

    private void BT_raw_materialsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_raw_materialsMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(ClickColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
        
    }//GEN-LAST:event_BT_raw_materialsMousePressed

    private void BT_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ordersMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(ClickColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
        
    }//GEN-LAST:event_BT_ordersMousePressed

    private void BT_product_simulationsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_product_simulationsMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(ClickColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_product_simulationsMousePressed

    private void BT_shopsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_shopsMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(ClickColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_shopsMousePressed

    private void BT_transport_vehiclesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_transport_vehiclesMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(ClickColor);
    }//GEN-LAST:event_BT_transport_vehiclesMousePressed

    private void BT_accountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_accountMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(ClickColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_accountMousePressed

    private void BT_job_applicationsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_job_applicationsMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(ClickColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_job_applicationsMousePressed

    private void BT_business_partnersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_business_partnersMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(ClickColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_business_partnersMousePressed

    private void BT_sales_personsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_sales_personsMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(ClickColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_sales_personsMousePressed

    private void BT_managersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_managersMousePressed
        // TODO add your handling code here:
        BT_employees.setBackground(DefaultColor);
        BT_account.setBackground(DefaultColor);
        BT_business_partners.setBackground(DefaultColor);
        BT_customers.setBackground(DefaultColor);
        BT_departmens.setBackground(DefaultColor);
        BT_job_applications.setBackground(DefaultColor);
        BT_managers.setBackground(ClickColor);
        BT_orders.setBackground(DefaultColor);
        BT_product_simulations.setBackground(DefaultColor);
        BT_production_machines.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        BT_raw_materials.setBackground(DefaultColor);
        BT_sales_persons.setBackground(DefaultColor);
        BT_shops.setBackground(DefaultColor);
        BT_suppliers.setBackground(DefaultColor);
        BT_transport_vehicles.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_managersMousePressed

    private void BT_departmensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_departmensActionPerformed
        // TODO add your handling code here:
        JInternalFrame_department frame_department = new JInternalFrame_department();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_department).setVisible(true);
    }//GEN-LAST:event_BT_departmensActionPerformed

    private void BT_suppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_suppliersActionPerformed
        // TODO add your handling code here:
        JInternalFrame_supplier frame_supplier = new JInternalFrame_supplier();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_supplier).setVisible(true);
    }//GEN-LAST:event_BT_suppliersActionPerformed

    private void BT_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_customersActionPerformed
        // TODO add your handling code here:
        JInternalFrame_customer frame_customer = new JInternalFrame_customer();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_customer).setVisible(true);
    }//GEN-LAST:event_BT_customersActionPerformed

    private void BT_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_productsActionPerformed
        // TODO add your handling code here:
        JInternalFrame_product frame_product = new JInternalFrame_product();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_product).setVisible(true);
    }//GEN-LAST:event_BT_productsActionPerformed

    private void BT_production_machinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_production_machinesActionPerformed
        // TODO add your handling code here:
        JInternalFrame_productionMachine frame_productionMachine = new JInternalFrame_productionMachine();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_productionMachine).setVisible(true);
    }//GEN-LAST:event_BT_production_machinesActionPerformed

    private void BT_raw_materialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_raw_materialsActionPerformed
        // TODO add your handling code here:
        JInternalFrame_rawMaterial frame_rawMaterial = new JInternalFrame_rawMaterial();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_rawMaterial).setVisible(true);
    }//GEN-LAST:event_BT_raw_materialsActionPerformed

    private void BT_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ordersActionPerformed
        // TODO add your handling code here:
        JInternalFrame_order frame_order = new JInternalFrame_order();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_order).setVisible(true);
    }//GEN-LAST:event_BT_ordersActionPerformed

    private void BT_product_simulationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_product_simulationsActionPerformed
        // TODO add your handling code here:
        JInternalFrame_productSimulation frame_productSimulation = new JInternalFrame_productSimulation();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_productSimulation).setVisible(true);
    }//GEN-LAST:event_BT_product_simulationsActionPerformed

    private void BT_shopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_shopsActionPerformed
        // TODO add your handling code here:
        JInternalFrame_shop frame_shop = new JInternalFrame_shop();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_shop).setVisible(true);
    }//GEN-LAST:event_BT_shopsActionPerformed

    private void BT_transport_vehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_transport_vehiclesActionPerformed
        // TODO add your handling code here:
        JInternalFrame_transportVehicle frame_transportVehicle = new JInternalFrame_transportVehicle();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_transportVehicle).setVisible(true);
    }//GEN-LAST:event_BT_transport_vehiclesActionPerformed

    private void BT_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_accountActionPerformed
        // TODO add your handling code here:
        JInternalFrame_account frame_account = new JInternalFrame_account();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_account).setVisible(true);
    }//GEN-LAST:event_BT_accountActionPerformed

    private void BT_job_applicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_job_applicationsActionPerformed
        // TODO add your handling code here:
        JInternalFrame_jobApplication frame_jobApplication = new JInternalFrame_jobApplication();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_jobApplication).setVisible(true);
    }//GEN-LAST:event_BT_job_applicationsActionPerformed

    private void BT_business_partnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_business_partnersActionPerformed
        // TODO add your handling code here:
        JInternalFrame_categories frame_businessPartner = new JInternalFrame_categories();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_businessPartner).setVisible(true);
    }//GEN-LAST:event_BT_business_partnersActionPerformed

    private void BT_sales_personsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_sales_personsActionPerformed
        // TODO add your handling code here:
        JInternalFrame_salesPerson frame_salesPerson = new JInternalFrame_salesPerson();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_salesPerson).setVisible(true);
    }//GEN-LAST:event_BT_sales_personsActionPerformed

    private void BT_managersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_managersActionPerformed
        // TODO add your handling code here:
        JInternalFrame_manager frame_manager = new JInternalFrame_manager();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_manager).setVisible(true);
    }//GEN-LAST:event_BT_managersActionPerformed

    private void BT_employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_employeesActionPerformed
        // TODO add your handling code here:
        JInternalFrame_employee frame_employee = new JInternalFrame_employee();
        panel_jframe_areas.removeAll();
        panel_jframe_areas.add(frame_employee).setVisible(true);
    }//GEN-LAST:event_BT_employeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_manager_dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_manager_dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_manager_dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_manager_dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_manager_dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_account;
    private javax.swing.JButton BT_business_partners;
    private javax.swing.JButton BT_customers;
    private javax.swing.JButton BT_departmens;
    private javax.swing.JButton BT_employees;
    private javax.swing.JButton BT_exit;
    private javax.swing.JButton BT_job_applications;
    private javax.swing.JButton BT_managers;
    private javax.swing.JButton BT_orders;
    private javax.swing.JButton BT_product_simulations;
    private javax.swing.JButton BT_production_machines;
    private javax.swing.JButton BT_products;
    private javax.swing.JButton BT_raw_materials;
    private javax.swing.JButton BT_sales_persons;
    private javax.swing.JButton BT_shops;
    private javax.swing.JButton BT_suppliers;
    private javax.swing.JButton BT_transport_vehicles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panel_butons1;
    private javax.swing.JPanel panel_butons2;
    private javax.swing.JPanel panel_jframe_areas;
    // End of variables declaration//GEN-END:variables
}
