
import java.awt.Color;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mehme
 */
public class JFrame_sales_person_dashbord extends javax.swing.JFrame {
    Color DefaultColor ,ClickColor;

    /**
     * Creates new form JFrame_sales_person
     */
    public JFrame_sales_person_dashbord() {
        initComponents();
        ImageIcon img = new ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\dashboard.png");
        this.setIconImage(img.getImage());
        DefaultColor = new Color(248,248,255);
        ClickColor = new Color(117,255,17);
        JInternalFrame_sales_customer frame_sales_customer = new JInternalFrame_sales_customer();
        panel_areas.removeAll();
        panel_areas.add(frame_sales_customer).setVisible(true);
        
        BT_customers.setBackground(ClickColor);
        BT_orders.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BT_exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BT_customers = new javax.swing.JButton();
        BT_orders = new javax.swing.JButton();
        BT_products = new javax.swing.JButton();
        panel_areas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 20, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SHOP MANAGEMENT SYSTEM");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\car_shop.png")); // NOI18N

        BT_exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\close_window.png")); // NOI18N
        BT_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(809, 809, 809)
                        .addComponent(BT_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BT_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        BT_customers.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\customer (1).png")); // NOI18N
        BT_customers.setText("CUSTOMERS");
        BT_customers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        BT_customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_customersMousePressed(evt);
            }
        });
        BT_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_customersActionPerformed(evt);
            }
        });

        BT_orders.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\icons8-purchase-order-32.png")); // NOI18N
        BT_orders.setText("ORDERS");
        BT_orders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        BT_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_ordersMousePressed(evt);
            }
        });
        BT_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ordersActionPerformed(evt);
            }
        });

        BT_products.setIcon(new javax.swing.ImageIcon("C:\\Users\\mehme\\Desktop\\Factory Management System\\Factory Management System\\images\\automobile.png")); // NOI18N
        BT_products.setText("PRODUCTS");
        BT_products.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        BT_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_productsMousePressed(evt);
            }
        });
        BT_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_productsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(BT_customers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(BT_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(BT_products, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BT_products, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BT_orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_areas.setBackground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout panel_areasLayout = new javax.swing.GroupLayout(panel_areas);
        panel_areas.setLayout(panel_areasLayout);
        panel_areasLayout.setHorizontalGroup(
            panel_areasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_areasLayout.setVerticalGroup(
            panel_areasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_areas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_areas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BT_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_exitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.exit(0);
        
    }//GEN-LAST:event_BT_exitActionPerformed

    private void BT_customersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_customersMousePressed
        // TODO add your handling code here:
        BT_customers.setBackground(ClickColor);
        BT_orders.setBackground(DefaultColor);
        BT_products.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_customersMousePressed

    private void BT_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ordersMousePressed
        // TODO add your handling code here:
        BT_customers.setBackground(DefaultColor);
        BT_orders.setBackground(ClickColor);
        BT_products.setBackground(DefaultColor);
    }//GEN-LAST:event_BT_ordersMousePressed

    private void BT_productsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_productsMousePressed
        // TODO add your handling code here:
        BT_customers.setBackground(DefaultColor);
        BT_orders.setBackground(DefaultColor);
        BT_products.setBackground(ClickColor);
    }//GEN-LAST:event_BT_productsMousePressed

    private void BT_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ordersActionPerformed
        // TODO add your handling code here:
        JInternalFrame_sales_order frame_sales_order = new JInternalFrame_sales_order();
        panel_areas.removeAll();
        panel_areas.add(frame_sales_order).setVisible(true);
    }//GEN-LAST:event_BT_ordersActionPerformed

    private void BT_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_customersActionPerformed
        // TODO add your handling code here:
        JInternalFrame_sales_customer frame_sales_customer = new JInternalFrame_sales_customer();
        panel_areas.removeAll();
        panel_areas.add(frame_sales_customer).setVisible(true);
    }//GEN-LAST:event_BT_customersActionPerformed

    private void BT_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_productsActionPerformed
        // TODO add your handling code here:
        JInternalFrame_sales_product frame_sales_product = new JInternalFrame_sales_product();
        panel_areas.removeAll();
        panel_areas.add(frame_sales_product).setVisible(true);
    }//GEN-LAST:event_BT_productsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_sales_person_dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_sales_person_dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_sales_person_dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_sales_person_dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_sales_person_dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_customers;
    private javax.swing.JButton BT_exit;
    private javax.swing.JButton BT_orders;
    private javax.swing.JButton BT_products;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_areas;
    // End of variables declaration//GEN-END:variables
}
